services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./src:/app/src
            - ./nodemon.json:/app/nodemon.json
            - ./public:/app/public
        container_name: api
        ports:
            - '4000'
            - '4000:4000'
        command: npm run dev
        depends_on:
            - docker-database

    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certificates:/etc/nginx/certs
        depends_on:
            - api

    docker-database:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: api 
            POSTGRES_USER: api
            POSTGRES_DATABASE: api

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
