name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Pull Docker images
        run: docker-compose pull
      - name: Deploy using Docker Compose
        run: docker-compose up -d
